### ISSUE TITLE
No longer compatible with the latest AspNetCoreOData (8.0.11)

### ISSUE THREAD

**Issue by PieterBoeren** [jamerst/o-data-grid#1]
This library is no longer compatible with the latest version of AspNetCoreOData (8.0.11), they [added a check](https://github.com/OData/AspNetCoreOData/pull/621) which disallows empty $select and $expand (it's apparently not allowed in the OData specs).

Could those parameters be removed in the final query when empty?

**Comment by jamerst** [comment]
Apologies for the slow response, this is now addressed in v1.3.1
